# GitHub action to build TclMPI on Linux and run unit tests
name: "Unittest for Linux"

on:
  push:

  workflow_dispatch:

jobs:
  build:
    name: Linux Unit Test
    if: ${{ github.repository == 'akohlmey/tclmpi' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Install MPI and Tcl
      run: |
        sudo apt-get update
        sudo apt-get install mpi-default-bin mpi-default-dev ninja-build tcl tcl-dev

    - name: Building TclMPI via CMake
      shell: bash
      run: |
        cmake -B build . -G Ninja
        cmake --build build --verbose

    - name: Run Tests
      working-directory: build
      shell: bash
      run: ctest -V
