# GitHub action to build TclMPI on Linux and run unit tests
name: "Unittest for Linux"

on:
  push:
    branches: [cmake-support]

jobs:
  build:
    name: Linux Unit Test
    if: ${{ github.repository == 'akohlmey/tclmpi' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Building TclMPI via CMake
      shell: bash
      run: |
        cmake -B build .
        cmake --build build

    - name: Run Tests
      working-directory: build
      shell: bash
      run: ctest -V
